const nock = require('nock')

const returner = {
  albums: {
    href:
      'https://api.spotify.com/v1/search?query=tree&type=album&market=JP&offset=0&limit=20',
    items: [
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7HwzlRPa9Ad0I8rK0FPzzK',
            },
            href: 'https://api.spotify.com/v1/artists/7HwzlRPa9Ad0I8rK0FPzzK',
            id: '7HwzlRPa9Ad0I8rK0FPzzK',
            name: 'SEKAI NO OWARI',
            type: 'artist',
            uri: 'spotify:artist:7HwzlRPa9Ad0I8rK0FPzzK',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/1NF6OvO7LcY8f7m5rVxU1T',
        },
        href: 'https://api.spotify.com/v1/albums/1NF6OvO7LcY8f7m5rVxU1T',
        id: '1NF6OvO7LcY8f7m5rVxU1T',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/88de5806b104adca0d23f28400ab5fc1285c1f09',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/baae21257ba1893539add72aa11a3754bd80ceb8',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/d0490cf8d904e2e6f0484b0cd798f3776fbf8f5b',
            width: 64,
          },
        ],
        name: 'Tree',
        release_date: '2015-01-14',
        release_date_precision: 'day',
        total_tracks: 13,
        type: 'album',
        uri: 'spotify:album:1NF6OvO7LcY8f7m5rVxU1T',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/51Blml2LZPmy7TTiAg47vQ',
            },
            href: 'https://api.spotify.com/v1/artists/51Blml2LZPmy7TTiAg47vQ',
            id: '51Blml2LZPmy7TTiAg47vQ',
            name: 'U2',
            type: 'artist',
            uri: 'spotify:artist:51Blml2LZPmy7TTiAg47vQ',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/0VhBqdWCPCvkUAqtNhmOd6',
        },
        href: 'https://api.spotify.com/v1/albums/0VhBqdWCPCvkUAqtNhmOd6',
        id: '0VhBqdWCPCvkUAqtNhmOd6',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/9e503f80b7951048215270c457ff167e6c96626c',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/57ed0a0ca2c8bc793d67b1c1bb6c478f975a77a9',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/4f5c825357eead19516c0c2e0e49cad890231ccd',
            width: 64,
          },
        ],
        name: 'The Joshua Tree (Super Deluxe)',
        release_date: '1987-03-03',
        release_date_precision: 'day',
        total_tracks: 49,
        type: 'album',
        uri: 'spotify:album:0VhBqdWCPCvkUAqtNhmOd6',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4UXqAaa6dQYAk18Lv7PEgX',
            },
            href: 'https://api.spotify.com/v1/artists/4UXqAaa6dQYAk18Lv7PEgX',
            id: '4UXqAaa6dQYAk18Lv7PEgX',
            name: 'Fall Out Boy',
            type: 'artist',
            uri: 'spotify:artist:4UXqAaa6dQYAk18Lv7PEgX',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5nkUSlIhtoJZMOUlB0sNCp',
        },
        href: 'https://api.spotify.com/v1/albums/5nkUSlIhtoJZMOUlB0sNCp',
        id: '5nkUSlIhtoJZMOUlB0sNCp',
        images: [
          {
            height: 631,
            url:
              'https://i.scdn.co/image/63a37f32006eab70bd58c892e4098f2a84bb915e',
            width: 640,
          },
          {
            height: 296,
            url:
              'https://i.scdn.co/image/92f68545738413d443a97f3d394f222b4b8ea5bc',
            width: 300,
          },
          {
            height: 63,
            url:
              'https://i.scdn.co/image/5bc9f20320fba62aa1f5da7aab70ddf8db628207',
            width: 64,
          },
        ],
        name: 'From Under The Cork Tree',
        release_date: '2005-01-01',
        release_date_precision: 'day',
        total_tracks: 13,
        type: 'album',
        uri: 'spotify:album:5nkUSlIhtoJZMOUlB0sNCp',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6nVMMEywS5Y4tsHPKx1nIo',
            },
            href: 'https://api.spotify.com/v1/artists/6nVMMEywS5Y4tsHPKx1nIo',
            id: '6nVMMEywS5Y4tsHPKx1nIo',
            name: 'TVXQ!',
            type: 'artist',
            uri: 'spotify:artist:6nVMMEywS5Y4tsHPKx1nIo',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3syxKIJgi0KrdmLAIu86YG',
        },
        href: 'https://api.spotify.com/v1/albums/3syxKIJgi0KrdmLAIu86YG',
        id: '3syxKIJgi0KrdmLAIu86YG',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/71e612479f859868c3cc588a314e5f0ddf12106a',
            width: 632,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/f5f09d2f3f0c39e724ff6fb4662b397c55e67f7f',
            width: 296,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/8b2bda15b643ed5443e83d053ab180d05cbd9aae',
            width: 63,
          },
        ],
        name: 'TREE',
        release_date: '2014-03-05',
        release_date_precision: 'day',
        total_tracks: 14,
        type: 'album',
        uri: 'spotify:album:3syxKIJgi0KrdmLAIu86YG',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1ICvDKVEfMCQxp6G2IllNn',
            },
            href: 'https://api.spotify.com/v1/artists/1ICvDKVEfMCQxp6G2IllNn',
            id: '1ICvDKVEfMCQxp6G2IllNn',
            name: 'Jonas Sager',
            type: 'artist',
            uri: 'spotify:artist:1ICvDKVEfMCQxp6G2IllNn',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/4U4OcS44qZY2w9CCDiYryV',
        },
        href: 'https://api.spotify.com/v1/albums/4U4OcS44qZY2w9CCDiYryV',
        id: '4U4OcS44qZY2w9CCDiYryV',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/c028b7f6bae63753643c4c50e1fb37231a3acb8d',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/4791d13a56038f6282c1182ef7b0a9aa40cadc9b',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/c7d9c9716b1cda7a0beb656f62075d0d17817f76',
            width: 64,
          },
        ],
        name: 'Tree Thieves',
        release_date: '2018-03-23',
        release_date_precision: 'day',
        total_tracks: 25,
        type: 'album',
        uri: 'spotify:album:4U4OcS44qZY2w9CCDiYryV',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6LvbiOyZ8aOUWZ3isV32uB',
            },
            href: 'https://api.spotify.com/v1/artists/6LvbiOyZ8aOUWZ3isV32uB',
            id: '6LvbiOyZ8aOUWZ3isV32uB',
            name: 'Tak-Z',
            type: 'artist',
            uri: 'spotify:artist:6LvbiOyZ8aOUWZ3isV32uB',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/1JIAwWbDZHFILgqxA9qDMd',
        },
        href: 'https://api.spotify.com/v1/albums/1JIAwWbDZHFILgqxA9qDMd',
        id: '1JIAwWbDZHFILgqxA9qDMd',
        images: [
          {
            height: 596,
            url:
              'https://i.scdn.co/image/d21bd7180d2ba40bb61b031256df3f3422f7869a',
            width: 600,
          },
          {
            height: 298,
            url:
              'https://i.scdn.co/image/1e47c90ba0619aaffadf0b1e032995901a6b87af',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/645703d7aa0229b97e29b145dfd1a098132461da',
            width: 64,
          },
        ],
        name: 'A Tree Of Life',
        release_date: '2012-07-25',
        release_date_precision: 'day',
        total_tracks: 14,
        type: 'album',
        uri: 'spotify:album:1JIAwWbDZHFILgqxA9qDMd',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7LPp4MiQ8yxVUxhxipe0mm',
            },
            href: 'https://api.spotify.com/v1/artists/7LPp4MiQ8yxVUxhxipe0mm',
            id: '7LPp4MiQ8yxVUxhxipe0mm',
            name: 'GRAPEVINE',
            type: 'artist',
            uri: 'spotify:artist:7LPp4MiQ8yxVUxhxipe0mm',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/0t61jOq1hiMOlHb9xmCucN',
        },
        href: 'https://api.spotify.com/v1/albums/0t61jOq1hiMOlHb9xmCucN',
        id: '0t61jOq1hiMOlHb9xmCucN',
        images: [
          {
            height: 600,
            url:
              'https://i.scdn.co/image/e634aa0242ec2eda25dcac4ad009b88983718a8c',
            width: 600,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/f68f56ceff5965268d3b7381b18ac7c749ab5825',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/66758811768a073e01daed810f2114747dfd79b1',
            width: 64,
          },
        ],
        name: 'Burning tree',
        release_date: '2015-01-28',
        release_date_precision: 'day',
        total_tracks: 11,
        type: 'album',
        uri: 'spotify:album:0t61jOq1hiMOlHb9xmCucN',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7wBFjZMHsC6nfV0HOSd6uI',
            },
            href: 'https://api.spotify.com/v1/artists/7wBFjZMHsC6nfV0HOSd6uI',
            id: '7wBFjZMHsC6nfV0HOSd6uI',
            name: 'The Modern Jazz Quartet',
            type: 'artist',
            uri: 'spotify:artist:7wBFjZMHsC6nfV0HOSd6uI',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/2jWCwSSFr7rEy4E3c5zLyT',
        },
        href: 'https://api.spotify.com/v1/albums/2jWCwSSFr7rEy4E3c5zLyT',
        id: '2jWCwSSFr7rEy4E3c5zLyT',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/3e70eefab463c7674f722bdc7a32c8f0b518c647',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/47cd6cb11e83c37073ad3db3ab254b755a04ae50',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/01f6d1fad328ea8c22e93d04e5dc26c83726ee22',
            width: 64,
          },
        ],
        name: 'Under The Jasmin Tree / Space',
        release_date: '2010-01-01',
        release_date_precision: 'day',
        total_tracks: 10,
        type: 'album',
        uri: 'spotify:album:2jWCwSSFr7rEy4E3c5zLyT',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5xKp3UyavIBUsGy3DQdXeF',
            },
            href: 'https://api.spotify.com/v1/artists/5xKp3UyavIBUsGy3DQdXeF',
            id: '5xKp3UyavIBUsGy3DQdXeF',
            name: 'A Great Big World',
            type: 'artist',
            uri: 'spotify:artist:5xKp3UyavIBUsGy3DQdXeF',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/7vQKE8QwQSN744hZPWNHrW',
        },
        href: 'https://api.spotify.com/v1/albums/7vQKE8QwQSN744hZPWNHrW',
        id: '7vQKE8QwQSN744hZPWNHrW',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/5bc052e72f5c0ffe8b9552b5ac3bc382d10029f2',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/df610135027cf93dbaa31841f37ae3118fa40dce',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/b00005486da691856b3e94d635c95f3be8e7f23e',
            width: 64,
          },
        ],
        name: 'Wrap Me Up Under the Christmas Tree',
        release_date: '2018-11-16',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:7vQKE8QwQSN744hZPWNHrW',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5O4DsTkJ6z2eTSvIHZ6sDo',
            },
            href: 'https://api.spotify.com/v1/artists/5O4DsTkJ6z2eTSvIHZ6sDo',
            id: '5O4DsTkJ6z2eTSvIHZ6sDo',
            name: 'Plastic Tree',
            type: 'artist',
            uri: 'spotify:artist:5O4DsTkJ6z2eTSvIHZ6sDo',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/6HMvtsMoZihPWE3k7ufnfK',
        },
        href: 'https://api.spotify.com/v1/albums/6HMvtsMoZihPWE3k7ufnfK',
        id: '6HMvtsMoZihPWE3k7ufnfK',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/889ff7a838a850d481219b651f797e0b153ba864',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/8048ec4279f68063fc5567161ab84939e05494c6',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/42be60fc0beaacf2ce73fcc77fb37f9f2ec42e19',
            width: 64,
          },
        ],
        name: 'What Is " Plastic Tree " ?',
        release_date: '2007-07-13',
        release_date_precision: 'day',
        total_tracks: 8,
        type: 'album',
        uri: 'spotify:album:6HMvtsMoZihPWE3k7ufnfK',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4cvdQRyHmkSQSakUrW2oxv',
            },
            href: 'https://api.spotify.com/v1/artists/4cvdQRyHmkSQSakUrW2oxv',
            id: '4cvdQRyHmkSQSakUrW2oxv',
            name: 'Michael Bibi',
            type: 'artist',
            uri: 'spotify:artist:4cvdQRyHmkSQSakUrW2oxv',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/58oNJQhG4TvKk49KcE8yHg',
        },
        href: 'https://api.spotify.com/v1/albums/58oNJQhG4TvKk49KcE8yHg',
        id: '58oNJQhG4TvKk49KcE8yHg',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/f6604e086dc8b536c1b31a710d50ec8a9f5d1346',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/aa5153beae62fa487a3eb77a6ef8d33b7d784217',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/44a334b02e81e57c536304faaf9b9b9b43db88d6',
            width: 64,
          },
        ],
        name: 'Hanging Tree',
        release_date: '2018-11-16',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:58oNJQhG4TvKk49KcE8yHg',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3E5NLQpQbd0eJ18XO9zC0h',
            },
            href: 'https://api.spotify.com/v1/artists/3E5NLQpQbd0eJ18XO9zC0h',
            id: '3E5NLQpQbd0eJ18XO9zC0h',
            name: 'Seiko Matsuda',
            type: 'artist',
            uri: 'spotify:artist:3E5NLQpQbd0eJ18XO9zC0h',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3thbYH19Dox2vPCjcaHVOc',
        },
        href: 'https://api.spotify.com/v1/albums/3thbYH19Dox2vPCjcaHVOc',
        id: '3thbYH19Dox2vPCjcaHVOc',
        images: [
          {
            height: 567,
            url:
              'https://i.scdn.co/image/9421e141419c2afcff0e2e8e8fd4587025d7f109',
            width: 640,
          },
          {
            height: 266,
            url:
              'https://i.scdn.co/image/dd737af4048ad86f6e445e7d583ef749dc56a6cc',
            width: 300,
          },
          {
            height: 57,
            url:
              'https://i.scdn.co/image/af2237e9a880327294f19d6dc574f7a73d068dc5',
            width: 64,
          },
        ],
        name: 'Christmas Tree',
        release_date: '1991-11-21',
        release_date_precision: 'day',
        total_tracks: 9,
        type: 'album',
        uri: 'spotify:album:3thbYH19Dox2vPCjcaHVOc',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/51Blml2LZPmy7TTiAg47vQ',
            },
            href: 'https://api.spotify.com/v1/artists/51Blml2LZPmy7TTiAg47vQ',
            id: '51Blml2LZPmy7TTiAg47vQ',
            name: 'U2',
            type: 'artist',
            uri: 'spotify:artist:51Blml2LZPmy7TTiAg47vQ',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/4mULDK6YXrFXTfSwvwm4M3',
        },
        href: 'https://api.spotify.com/v1/albums/4mULDK6YXrFXTfSwvwm4M3',
        id: '4mULDK6YXrFXTfSwvwm4M3',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/f0ba9ce3f3045892ddc0009a8dcca4586a7b949a',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/1f2cd5513c3bd3727d3b310c9ea088507295b869',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/bcd4f81f04f16c4486cf66d975c994a73bbfc018',
            width: 64,
          },
        ],
        name: 'The Joshua Tree',
        release_date: '1987-03-10',
        release_date_precision: 'day',
        total_tracks: 25,
        type: 'album',
        uri: 'spotify:album:4mULDK6YXrFXTfSwvwm4M3',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/51Blml2LZPmy7TTiAg47vQ',
            },
            href: 'https://api.spotify.com/v1/artists/51Blml2LZPmy7TTiAg47vQ',
            id: '51Blml2LZPmy7TTiAg47vQ',
            name: 'U2',
            type: 'artist',
            uri: 'spotify:artist:51Blml2LZPmy7TTiAg47vQ',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5vBZRYu2GLA65nfxBvG1a7',
        },
        href: 'https://api.spotify.com/v1/albums/5vBZRYu2GLA65nfxBvG1a7',
        id: '5vBZRYu2GLA65nfxBvG1a7',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/f0ba9ce3f3045892ddc0009a8dcca4586a7b949a',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/1f2cd5513c3bd3727d3b310c9ea088507295b869',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/bcd4f81f04f16c4486cf66d975c994a73bbfc018',
            width: 64,
          },
        ],
        name: 'The Joshua Tree',
        release_date: '1987-03-10',
        release_date_precision: 'day',
        total_tracks: 11,
        type: 'album',
        uri: 'spotify:album:5vBZRYu2GLA65nfxBvG1a7',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/37hLlbtNh8yXKbVHK13gsp',
            },
            href: 'https://api.spotify.com/v1/artists/37hLlbtNh8yXKbVHK13gsp',
            id: '37hLlbtNh8yXKbVHK13gsp',
            name: 'ISSUGI',
            type: 'artist',
            uri: 'spotify:artist:37hLlbtNh8yXKbVHK13gsp',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/6xgxtmZd9K9WL2HEPI0zd7',
        },
        href: 'https://api.spotify.com/v1/albums/6xgxtmZd9K9WL2HEPI0zd7',
        id: '6xgxtmZd9K9WL2HEPI0zd7',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/66b4e3ed119b336d274ab9c44afa970199d05d8c',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/d78266e6a51189a03b4db06f7a85079856a98e0f',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/15d335f1668dd7df835f6aa49ce233fca06a5635',
            width: 64,
          },
        ],
        name: 'THE STORY OF 7INC TREE -Tree & Chambr-',
        release_date: '2018-08-18',
        release_date_precision: 'day',
        total_tracks: 15,
        type: 'album',
        uri: 'spotify:album:6xgxtmZd9K9WL2HEPI0zd7',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7H7kbnGiqnG8GYDtDALthl',
            },
            href: 'https://api.spotify.com/v1/artists/7H7kbnGiqnG8GYDtDALthl',
            id: '7H7kbnGiqnG8GYDtDALthl',
            name: 'Isato Nakagawa',
            type: 'artist',
            uri: 'spotify:artist:7H7kbnGiqnG8GYDtDALthl',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/6scj26E3tVRTzcBkkx5qRB',
        },
        href: 'https://api.spotify.com/v1/albums/6scj26E3tVRTzcBkkx5qRB',
        id: '6scj26E3tVRTzcBkkx5qRB',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/63411adf73a2c201f510b717424a80420266b8e8',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/7758412f472c5bdb434fe3913a21b1a32d316808',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/c26863624d42317eaf77732cd89ea2ccabdca50b',
            width: 64,
          },
        ],
        name: 'Tree Circle',
        release_date: '2011-08-24',
        release_date_precision: 'day',
        total_tracks: 13,
        type: 'album',
        uri: 'spotify:album:6scj26E3tVRTzcBkkx5qRB',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/67ZdpNN4rYCioiPhfFUQdd',
            },
            href: 'https://api.spotify.com/v1/artists/67ZdpNN4rYCioiPhfFUQdd',
            id: '67ZdpNN4rYCioiPhfFUQdd',
            name: 'J. LAMOTTA すずめ',
            type: 'artist',
            uri: 'spotify:artist:67ZdpNN4rYCioiPhfFUQdd',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5YecWXqhCDHzB4qOAlFDgy',
        },
        href: 'https://api.spotify.com/v1/albums/5YecWXqhCDHzB4qOAlFDgy',
        id: '5YecWXqhCDHzB4qOAlFDgy',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/39d71c1aea48477a81e485eaa298a627d0b71d76',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/4430f9e0dc36a1169d69656f1a2bbeee5445c144',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/8cda9d27204bc28829f0a7e7aacf539b73e2a461',
            width: 64,
          },
        ],
        name: 'Conscious Tree',
        release_date: '2018-02-02',
        release_date_precision: 'day',
        total_tracks: 10,
        type: 'album',
        uri: 'spotify:album:5YecWXqhCDHzB4qOAlFDgy',
      },
      {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6O0rWDT0LuZk9Cpe45kbcx',
            },
            href: 'https://api.spotify.com/v1/artists/6O0rWDT0LuZk9Cpe45kbcx',
            id: '6O0rWDT0LuZk9Cpe45kbcx',
            name: 'Anna Elizabeth Laube',
            type: 'artist',
            uri: 'spotify:artist:6O0rWDT0LuZk9Cpe45kbcx',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3pALJvtTxIm5i1aYlaZDnA',
        },
        href: 'https://api.spotify.com/v1/albums/3pALJvtTxIm5i1aYlaZDnA',
        id: '3pALJvtTxIm5i1aYlaZDnA',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/d973a0f6eec780a3490b9cae15c21f19b77ef320',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/4d0acb6d521ab9a05b65f447519e7367fbfbc360',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/b57d4c1944f34d96458f8d24aff2e7c4e2f17d44',
            width: 64,
          },
        ],
        name: 'Tree',
        release_date: '2016-09-09',
        release_date_precision: 'day',
        total_tracks: 9,
        type: 'album',
        uri: 'spotify:album:3pALJvtTxIm5i1aYlaZDnA',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6TLwD7HPWuiOzvXEa3oCNe',
            },
            href: 'https://api.spotify.com/v1/artists/6TLwD7HPWuiOzvXEa3oCNe',
            id: '6TLwD7HPWuiOzvXEa3oCNe',
            name: 'Oliver Tree',
            type: 'artist',
            uri: 'spotify:artist:6TLwD7HPWuiOzvXEa3oCNe',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5AelTZUdahNA7besdaECfD',
        },
        href: 'https://api.spotify.com/v1/albums/5AelTZUdahNA7besdaECfD',
        id: '5AelTZUdahNA7besdaECfD',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/a4df6b54552a351365fa0f30a6decd413919bf13',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/08d49c66e154b9f2897a9fde8623ab07b2d68a35',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/f2112ba67d35a1dfeeec7f6466f5d8f00e3aa880',
            width: 64,
          },
        ],
        name: 'Alien Boy EP',
        release_date: '2018-02-16',
        release_date_precision: 'day',
        total_tracks: 6,
        type: 'album',
        uri: 'spotify:album:5AelTZUdahNA7besdaECfD',
      },
      {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4u1nYxjl132D6rcMeYQ6Zz',
            },
            href: 'https://api.spotify.com/v1/artists/4u1nYxjl132D6rcMeYQ6Zz',
            id: '4u1nYxjl132D6rcMeYQ6Zz',
            name: 'Rival',
            type: 'artist',
            uri: 'spotify:artist:4u1nYxjl132D6rcMeYQ6Zz',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2jrBiKykLqcIp2S7GLiahy',
            },
            href: 'https://api.spotify.com/v1/artists/2jrBiKykLqcIp2S7GLiahy',
            id: '2jrBiKykLqcIp2S7GLiahy',
            name: 'Cadmium',
            type: 'artist',
            uri: 'spotify:artist:2jrBiKykLqcIp2S7GLiahy',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3ZVW9s2Xb8NQDzwEqElbNq',
            },
            href: 'https://api.spotify.com/v1/artists/3ZVW9s2Xb8NQDzwEqElbNq',
            id: '3ZVW9s2Xb8NQDzwEqElbNq',
            name: 'Rosendale',
            type: 'artist',
            uri: 'spotify:artist:3ZVW9s2Xb8NQDzwEqElbNq',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/0z24XzwOR8RobYQxacyDpS',
        },
        href: 'https://api.spotify.com/v1/albums/0z24XzwOR8RobYQxacyDpS',
        id: '0z24XzwOR8RobYQxacyDpS',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/cecf743d6f03d8777628e95804380f9effcb5f5c',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/b708ee6cc83efe7d82441c1927879031bb392d7b',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/95e8fa007b0100dea9613a25c3bd54e7d715c994',
            width: 64,
          },
        ],
        name: 'Willow Tree',
        release_date: '2018-11-23',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:0z24XzwOR8RobYQxacyDpS',
      },
    ],
    limit: 20,
    next:
      'https://api.spotify.com/v1/search?query=tree&type=album&market=JP&offset=20&limit=20',
    offset: 0,
    previous: null,
    total: 6314,
  },
}

nock('https://api.spotify.com')
  .get('/v1/search?q=tree&type=album')
  .reply(200, returner)
